>>> import turtle
>>> tom = turtle.Turtle()
>>> tom.circle(100)
>>> type(tom)
<class 'turtle.Turtle'>
>>> nonte = turtle.Turtle()
>>> fonte = turtle.Turtle()
>>> nonte.shape("circle")
>>> fonte.shape("square")
>>> nonte.left(40)
>>> nonte.forward(100)
>>> fonte.backward(200)
>>> monte = turtle.Turtle()
>>> monte.setpos(-200,-200)
>>> monte.forward(30)
>>> monte.clear()
>>> nonte.clear ()
>>> fonte.clear()
>>> fonte.shape("triangle")
>>> monte.shape("square")
